// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv09x5Q2jPFeUMQUtM3AbCtWSRoxIS0Zc',
    appId: '1:248706637356:web:c0b8dd98dee821550b3b89',
    messagingSenderId: '248706637356',
    projectId: 'solana-hack-day',
    authDomain: 'solana-hack-day.firebaseapp.com',
    storageBucket: 'solana-hack-day.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUEJaeZ5GBAGnk5LeVRVcXNxFy0cVDdKk',
    appId: '1:248706637356:android:88cfc4b6f0ca7fcb0b3b89',
    messagingSenderId: '248706637356',
    projectId: 'solana-hack-day',
    storageBucket: 'solana-hack-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmYBFW0k0HJJOV1gLwA6wZUITsTlcCNWs',
    appId: '1:248706637356:ios:608511aab62cead30b3b89',
    messagingSenderId: '248706637356',
    projectId: 'solana-hack-day',
    storageBucket: 'solana-hack-day.appspot.com',
    androidClientId: '248706637356-2jkp2106jiio7e71m3sldcde7rdpcehg.apps.googleusercontent.com',
    iosClientId: '248706637356-6f7k8uif388dnjdoce1bn4v3qjhhufre.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientDapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmYBFW0k0HJJOV1gLwA6wZUITsTlcCNWs',
    appId: '1:248706637356:ios:608511aab62cead30b3b89',
    messagingSenderId: '248706637356',
    projectId: 'solana-hack-day',
    storageBucket: 'solana-hack-day.appspot.com',
    androidClientId: '248706637356-2jkp2106jiio7e71m3sldcde7rdpcehg.apps.googleusercontent.com',
    iosClientId: '248706637356-6f7k8uif388dnjdoce1bn4v3qjhhufre.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientDapp',
  );
}
